export class Locker {
    // lckrid: any= ''  ;
    // appstamp: string= ''  ;
    // actype: string= ''  ;
    // oprbrancd: string= ''  ;
    // brancd:string= ''  ;
    // actnum: string= ''  ;
    // remarks: string= ''  ;
    // oprtimstamp:string= ''  ;
    // paystat: string= ''  ;
    // cuscod: string= ''  ;
    // oprstamp: string= ''  ;
    // update_BY: string= ''  ;
    // update_DATE:string= ''  ;
    // drwrid:string= ''  ;
    // reldate:string= ''  ;
    // appflg: string= ''  ;
    // apptimstamp: string= ''  ;
    // relid :any= ''  ;
    
    RELID :any= ''  ;
    OPRBRANCD : string= ''  ;
    CUSCOD : string= ''  ;
    BRANCD : string= ''  ;
    ACTYPE : string= ''  ;
    ACTNUM : string= ''  ;
    LCKRID :any= ''  ;
    DRWRID :any= ''  ;
    RELDATE : string= ''  ;
    PAYSTAT : string= ''  ;
    REMARKS : string= ''  ;
    OPRSTAMP : string= ''  ;
    OPRTIMSTAMP : string= ''  ;
    UPDATE_BY : string= ''  ;
    UPDATE_DATE: string= ''  ;
    APPFLG : string= ''  ;
    APPSTAMP : string= ''  ;
    APPTIMSTAMP : string= ''  ;
}
